### ISSUE TITLE
ShellyGas support

### ISSUE THREAD

**Issue by pizzulicchio** [enesbcs/Shelly_MQTT#80]
Hi,
i'd like to use your plugin for discovery my new ShellyGas with domoticz but it seems to not be supported. 
What do you need for make it compatible with your plugin ?

**Comment by enesbcs** [comment]
In a perfect world, i need a device to implement & test it. :)

Otherwise if you can check if mqtt messages sent by your devices are meet with the official API:
https://shelly-api-docs.shelly.cloud/#shelly-gas-mqtt

And then a brainstorming can be started to guess what kind of Domoticz device will be the best to represent incoming data. For the first sight "operation", "gas" and "self_test" can be selector box - however i do not know if all three is needed or can it be merged to one virtual device, or only "gas" needed... and last of them "concentration" can go into a Domoticz "Custom sensor".

**Comment by pizzulicchio** [comment]
Thank you for your response!
I'm not a programmer but I can try to find something util.

This is the MQTT log of the device:

MQTT message: shellies/shellygas-10521CF29E18/sensor/operation normal
MQTT message: shellies/shellygas-10521CF29E18/sensor/gas none
MQTT message: shellies/shellygas-10521CF29E18/sensor/self_test not_completed
MQTT message: shellies/shellygas-10521CF29E18/valve/0/state not_connected
MQTT message: shellies/shellygas-10521CF29E18/sensor/concentration 0

If I can afford to give an opinion on this, I would prefer 4 separate objects:
operation
gas
self_test
concentration

After the firmware update there is a new section , named "valve" because it's possible to integrate this sensor with an electric valve so it's possible to close the gas in case of gas leak.

If you need some screenshot or other infos, let me know.

Thank you again for your time and your patience!

Have a nice day

**Comment by enesbcs** [comment]
I will try to figure out something based on mqtt samples.

**Comment by enesbcs** [comment]
Some support added at commit https://github.com/enesbcs/Shelly_MQTT/commit/636e4ee797963b42d709f2e1e2d9cbc49dbe34f2

**Comment by pizzulicchio** [comment]
Great! It works now. 
Thank you very very much!

**Comment by enesbcs** [comment]
valve is not yet implemented i guess it works like relay

**Comment by pizzulicchio** [comment]
Me too I think so, for me, we can close the issue.
