### ISSUE TITLE
Shelly 2.5 support energy reporting per channel

### ISSUE THREAD

**Issue by enesbcs** [enesbcs/Shelly_MQTT#9]
Reference to:
http://www.domoticz.com/forum/viewtopic.php?f=65&t=25656&sid=823e9e5fd3492f59875d0e6a568613ea&start=100#p216186

**Comment by enesbcs** [comment]
Issue is addressed in commit https://github.com/enesbcs/Shelly_MQTT/commit/2e66e08ec92553a90e679a96045e84baba87a628. Testing and feedback needed.

**Comment by joba-1** [comment]
not sure what kind of feedback you want, but anyways:

I have a shelly 2.5. 
I use your plugin (git pulled right now) with domoticz 4.10532 and python 3.4.
Previously it did not work (python math import error in domoticz.log)
Now it does (due to not using the random function for client id): Thanks!

It reports one energy reading, not two, Which is ok, I guess, because I use roller shutter mode.
Reported values look reasonable.

**Comment by enesbcs** [comment]
Thanks for feedback. Energy reporting should work now in each channels independently. In shutter mode, there are no 0 or 1 channel, so it seems OK.

**Comment by enesbcs** [comment]
Closed as no new feedbacks, considered done.
